### ISSUE TITLE
Unnecessary Alert Prompt Triggered During Routing Reordering

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#138]
## Note 
When a user reorders a routing downwards via drag and drop and releases the cursor over the route name label, an alert prompt is erroneously triggered, asking the user to stay or leave the page. This issue is replicable at every point on the route name label except for the reorder chip.

## Expected behavior
Ideally, there should be no alert message generated when reordering a routing downwards via drag and drop and releasing the cursor over the route name label. Users should be able to perform this action seamlessly without any unnecessary interruptions.

## Steps to reproduce the issue
Log in to the application using valid credentials.
Click on any brokering run to see the routing configured for the run.
Navigate to the routing management section.
Attempt to reorder a routing downwards via drag and drop.
Release the cursor over the route name label.
Observe the alert prompt asking the user to stay or leave the page.

## Environment details
App version : v1.1.0
App environment : UAT

## Additional information
https://jam.dev/c/e3215fe9-f4c9-461b-8ffc-ba46cf35ba56

**Comment by dt2patel** [comment]
Seems like this issue is happening if the user releases the card when the cursor is outside of the "re-ordering" chip. Not sure what the best solution here is @ymaheshwari1 if there is no way to fix this with existing UI we can think of a new UI

**Comment by ymaheshwari1** [comment]
> Seems like this issue is happening if the user releases the card when the cursor is outside of the "re-ordering" chip. Not sure what the best solution here is @ymaheshwari1 if there is no way to fix this with existing UI we can think of a new UI

I will check once on this.
