### ISSUE TITLE
Save Button Enablement Issue After Resetting Routing Changes

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#139]
## Note
Same issue is occurring for save button on routing rule page.
When a user opens the modal for route/rule filter/sort on the inventory rule page, the 'Save' button appears enabled within the modal, even when no changes have been made.

## Expected behavior
The save button should remain disabled after resetting routing changes to the original settings, indicating that no modifications have been made.

## Steps to reproduce the issue
Log in to the application using valid credentials.
Click on any brokering run to see the routing configured for the run.
Navigate to the routing management section.
Make changes to the routing settings.
Revert the changes back to the original settings.
Notice that the save button becomes enabled, allowing for saving despite no actual changes being made.

## Environment details
App version : v1.1.0
App environment : UAT

## Additional information
https://jam.dev/c/3196af19-f7b0-460b-8b46-a5619ff98350

**Comment by dt2patel** [comment]
I think it's ok if the app is only detecting change in the state of the screen. I don't think the app should be expected to know when you've undone a change. This is not something we'll pick in the near future so closing this task for now
