### ISSUE TITLE
Routing Name Truncation Issue on UI

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#140]
## Note
Same issue is occurring for rule name also on routing rule page.

## Expected behavior
Routing names should be wrapped appropriately to ensure complete visibility on the UI, even if they exceed the available space.
Users should be able to view the full routing names without any truncation, facilitating easy identification and comprehension.

## Steps to reproduce the issue
Navigate to the section of the UI where routing names are displayed.
Observe routing names that are longer than the available space.
Notice that instead of wrapping to accommodate the full name, the routing names are truncated.
Attempt to discern the complete routing names, which may be challenging due to truncation.

## Environment details
App version : v1.1.0
App environment : UAT

## Additional information
https://jam.dev/c/c997ad44-99f4-47db-afbf-c14b8aecbe5d

**Comment by ymaheshwari1** [comment]
> This is a pretty low priority issue since the likely hood that someone will actually do this is pretty low. So @ymaheshwari1 if you haven't already finished this fix, we can skip this.

Ok, Sir moving this  to backlog.

**Comment by dt2patel** [comment]
Closing issue since we will not be picking it in near future
