### ISSUE TITLE
Persistence of empty filters in Order Route/Inventory Rules on saving.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#154]
## Expected behavior
After saving changes to an order route/inventory rule where a filter is selected but no value is chosen, the filter should not persist in the UI. It should be automatically removed upon saving the changes.

## Steps to reproduce the issue
Create a new order route. 
Open it and then navigate to the inventory rule management section.
Choose a filter without selecting any value for it.
Save the changes.
Create a new inventory rule and select it to edit.
Choose a filter without selecting any value for it.
Save the changes.
Observe that the filter remains displayed in the UI, even though it should have been removed due to the absence of a selected value.

## Environment details
App version : V2.25.0
App environment : DEV

## Additional information
https://jam.dev/c/4a71608a-75c2-4fdd-bd8a-160b6de8c336

**Comment by dt2patel** [comment]
The current UI is expected and we will not change it.
