### ISSUE TITLE
No filter and sort order empty state

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#165]
## What is the motivation for adding/enhancing this feature?

No order filter: "Add order filters. br All orders in all parkings will be attempted if no filter is applied."
(if the opposite is true, and no orders are picked)
"Add order filters. br No orders will be routed if at least one filter is not applied."
No sort order: "Add sorting rules. br Orders will be brokered based on created date if no sorting is specified."

**Comment by ymaheshwari1** [comment]
Moving it to backlog as we need to add the empty states for inventory filter and sort cards as well, but currently not having proper messages to be displayed based on the default conditions.

**Comment by Adameddy26** [comment]
verified and working fine in release v1.2.0.
https://jam.dev/c/e0aef19b-84c7-47c3-83f6-074d460dac2d

**Comment by dt2patel** [comment]
Inventory Rule Filter:

Add inventory lookup filters.

br

All facilities enabled for online fulfillment will be attempted for brokering if no filter is applied.

Lear more about enabling a facility for [online fulfillment](link to https://docs.hotwax.co/documents/v/system-admins/administration/facilities/configure-fulfillment-capacity)

<img width="744" alt="Screenshot 2024-08-14 at 2 14 14 PM" src="https://github.com/user-attachments/assets/c336aa64-e8aa-43bd-a76c-42674676e287">

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.5.0. Hence, closing this ticket.
