### ISSUE TITLE
Allow order filter exclusion

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#212]
## What is the motivation for adding/enhancing this feature?

Allow order filters to be exclusion based. Need to build UI for this. Backend support exists, need front end support

**Comment by ymaheshwari1** [comment]
Closing this against another issue having UI for the same https://github.com/hotwax/order-routing/issues/248

**Comment by dt2patel** [comment]
UI added here: 

<img width="1045" alt="Screenshot 2024-08-14 at 12 56 26 PM" src="https://github.com/user-attachments/assets/b2f345c0-2502-479e-a2b3-839da9e1d065">


<img width="960" alt="Screenshot 2024-08-14 at 12 56 45 PM" src="https://github.com/user-attachments/assets/dea53ab9-42cd-4500-9364-7601ce257547">
