### ISSUE TITLE
Show consistent status icons on items

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#228]
## What is the motivation for adding/enhancing this feature?

All ion-items showing routing status should show the pulse icon for consistency. Routing group, routing and inventory lookup.

<img width="514" alt="Screenshot 2024-06-13 at 6 27 35 PM" src="https://github.com/hotwax/order-routing/assets/60128132/e994efa6-e4da-4e94-b4d6-75c110241b59">

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v1.4.0. Hence, closing this ticket.
https://jam.dev/c/749e0ca1-c21e-4e48-9a0e-95bd87099d78
