### ISSUE TITLE
Add order item group split toggle

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#231]
## What is the motivation for adding/enhancing this feature?

Add support for the order item group split toggle. This toggle is an option that is available along side the regular allow partial allocation toggle.

This toggle can only be enabled if allow partial allocation is enabled. Otherwise this option will remain hidden and toggled off.

<img width="578" alt="Screenshot 2024-06-15 at 8 37 27 PM" src="https://github.com/hotwax/order-routing/assets/60128132/1780cb6f-22f8-434f-b4c4-02756c418179">

**Comment by ymaheshwari1** [comment]
EnumId to apply the item group split check is: IIP_SPLIT_ITEM_GROUP, enumTypeId: INV_FILTER_PRM_TYPE.
Need to add a check in the filter modal to exclude this enum from displaying on the UI.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.4.0. Hence, closing this ticket.
