### ISSUE TITLE
Sales Channel Filter Dropdown is Empty in Route Filters

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#232]
## Current behavior
The sales channel filter dropdown is empty, and no values are present inside it.

## Expected behavior
The sales channel filter dropdown should display a list of available sales channels to select from.

## Steps to reproduce the issue
Open the App.
Open any run. Inside the run, open ant route.
Select sales channel filter.
Click on the sales channel filter dropdown.
Observe the issue.

## Environment details
App version : V1.3.0
App environment : UAT

## Additional information
![Screenshot from 2024-06-20 19-37-28](https://github.com/hotwax/fulfillment/assets/158989293/9c703d24-bf10-4232-a48b-2dbb19121582)

**Comment by ymaheshwari1** [comment]
Fixed in https://github.com/hotwax/order-routing/issues/235

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.4.0. Hence, closing this issue.
![Screenshot from 2024-08-13 11-50-30](https://github.com/user-attachments/assets/25f0e868-67b5-412f-9c73-7007a4671c8a)
