### ISSUE TITLE
Redundancy of "New Run" button in empty state

### ISSUE THREAD

**Issue by amanmodi021** [hotwax/order-routing#233]
![orderrouting](https://github.com/hotwax/order-routing/assets/171926103/83d6fd65-244d-4e90-a77a-8e6432d16dfa)

## Problem Statement
Two buttons with different names but the same function on the same page create confusion.

## Solution
In the empty state, there should be a single button below the image cause it draws the user's attention to the center, and it clearly explains its function. 
Once the empty state ends, the top right button should be visible. 

"Arrow" icon should be replaced with "Plus" icon in the "Create Brokering Run" button

**Comment by Adameddy26** [comment]
Verified in release v1.5.0 and found that 'Arrow' icon is not replaced with the 'Plus'  icon. Hence, reopening this ticket.

**Comment by Adameddy26** [comment]
Separate issue has been raised for the icon issue. 
https://github.com/hotwax/order-routing/issues/266
Hence, marking this ticket as closed
