### ISSUE TITLE
Order group splitting option

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#242]
## What is the motivation for adding/enhancing this feature?

Move order group splitting option to Actions section. For user it should feel like splitting order experience:

<img width="980" alt="Screenshot 2024-07-16 at 2 36 53 PM" src="https://github.com/user-attachments/assets/aa917b56-ee6d-4ee8-9304-6d676b6c6f6b">

**Comment by ymaheshwari1** [comment]
@dt2patel Its currently inside the `Actions` section only, or am I understanding it wrong?
