### ISSUE TITLE
Use card header and title in group page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing#243]
## What is the motivation for adding/enhancing this feature?

The group page should show the group title and id in ion card syntax

<img width="542" alt="Screenshot 2024-07-16 at 4 29 50 PM" src="https://github.com/user-attachments/assets/222fcb9e-9e6c-4430-ae74-512d69c4a287">

**Comment by dt2patel** [comment]
Adding more UI changes directly into this ticket:

Draft badge should be grey not primary
<img width="307" alt="Screenshot 2024-07-16 at 4 32 22 PM" src="https://github.com/user-attachments/assets/b0ae5d6f-df61-4d0b-8646-e4cff8545ed9">

**Comment by dt2patel** [comment]
<img width="220" alt="Screenshot 2024-07-16 at 4 32 53 PM" src="https://github.com/user-attachments/assets/bd3074ae-4668-4123-acbb-d52eb9edee09">
This should only say "rule" no "s" when single rule is archived

**Comment by dt2patel** [comment]
<img width="208" alt="Screenshot 2024-07-16 at 4 34 28 PM" src="https://github.com/user-attachments/assets/af2510a1-b3ed-438e-847f-ed5c25b47aaf">
For routing group color of draft badge should also be grey

**Comment by dt2patel** [comment]
<img width="244" alt="Screenshot 2024-07-16 at 4 34 54 PM" src="https://github.com/user-attachments/assets/ae9e097f-a440-43e4-b046-8541372b106b">
Change title to "Routing run" instead of actual name. Name is already available on card title

**Comment by dt2patel** [comment]
<img width="342" alt="Screenshot 2024-07-16 at 4 45 12 PM" src="https://github.com/user-attachments/assets/ee124c7d-973d-4c17-9700-73d8c63b2606">
Change name of page to "Routing details"

**Comment by dt2patel** [comment]
<img width="490" alt="Screenshot 2024-07-16 at 4 47 38 PM" src="https://github.com/user-attachments/assets/58dd80e9-4edd-4ea7-b3fc-7c98837759c8">
Add some padding top to this section overall. There is not enough space between it and the header

**Comment by dt2patel** [comment]
<img width="674" alt="Screenshot 2024-07-16 at 4 53 16 PM" src="https://github.com/user-attachments/assets/c5f944f9-1bdc-44ff-a9fc-54eceb37a228">
Only show option for custom sequence with facility group is selected in the filter criteria

**Comment by dt2patel** [comment]
Move archived inventory lookups to archived line item. When clicking on archive item, open modal like we open for order routings archive process:

<img width="701" alt="Screenshot 2024-07-16 at 7 05 24 PM" src="https://github.com/user-attachments/assets/3d655810-345a-4b63-bc8d-38cf7263d433">

**Comment by dt2patel** [comment]
Are we good to close this issue @ymaheshwari1 ?

**Comment by ymaheshwari1** [comment]
> Are we good to close this issue @ymaheshwari1 ?

Not tested yet, assigning @Adameddy26

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.5.0. Hence, closing this ticket.
