### ISSUE TITLE
Make partial allocation as selected when selecting promise date and partial group items when selecting partial allocation

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing#257]
## What is the motivation for adding/enhancing this feature?

Currently when selecting promise date we enable the partial allocation value on the UI but are not updating its value in the backend.
Another case is that when selecting partial allocation, the group items allocation also needs to be updated as when partial allocation is selected we allow partial allocation for grouped items.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.5.0. Hence, closing it.
