### ISSUE TITLE
Change Icon for "Create Brokering Run" Button

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing#266]
## Description 
Currently, the "Create Brokering Run" button on the Order Routing app's Brokering Run page displays an arrow icon (->). This enhancement proposes changing the icon to a '+' icon for better clarity and alignment with user expectations.

**Comment by Adameddy26** [comment]
Related issue : https://github.com/hotwax/order-routing/issues/233

**Comment by coolnj4** [comment]
I’ve fixed the issue in [PR #275 ](https://github.com/hotwax/order-routing/pull/275) where I changed the arrow icon (->) for the "Create Brokering Run" button to a '+' icon. This update improves clarity and aligns with user expectations, as suggested.

Please review the changes and let me know if any further adjustments are needed!

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v1.7.0. Hence, closing this issue.
