### ISSUE TITLE
Rule name is not getting updated

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing#269]
## Current behavior

When trying to update the rule name, its displayed as updated until we are on the screen, but after refresh or page change the rule name gets changed to the previous value

## Expected behavior

Rule name should update on the server as well, so that it does not gets changed on page refresh

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.7.0. Hence, closing this issue.
